export interface Tool {
  id: string;
  name: string;
  description: string;
  category: 'Dev' | 'Design' | 'Produtividade' | 'Ciência' | 'Segurança' | 'Diversos' | 'Comunidade';
  icon: string;
}

export const TOOLS: Tool[] = [
  { id: '01', name: 'Esquema JSON para Zod', description: 'Transforma JSON em schemas de validação Zod (TS).', category: 'Dev', icon: 'Code2' },
  { id: '02', name: 'Visualizador de Regex', description: 'Explica graficamente como uma expressão regular funciona.', category: 'Dev', icon: 'Search' },
  { id: '03', name: 'Formatador SQL', description: 'Formata queries SQL complexas localmente.', category: 'Dev', icon: 'Database' },
  { id: '04', name: 'CSV para Tabela HTML', description: 'Converte arquivos CSV em tabelas HTML estilizadas.', category: 'Dev', icon: 'Table' },
  { id: '05', name: 'Decodificador JWT Offline', description: 'Decodifica tokens JWT sem enviar dados ao servidor.', category: 'Dev', icon: 'Key' },
  { id: '06', name: 'Visualizador de Cron', description: 'Traduz expressões de cron para linguagem humana.', category: 'Dev', icon: 'Clock' },
  { id: '07', name: 'Codificador de Entidades HTML', description: 'Converte caracteres especiais em entidades HTML.', category: 'Dev', icon: 'FileCode' },
  { id: '08', name: 'Gerador de Arquivo .env', description: 'Interface visual para criar arquivos .env baseados em templates.', category: 'Dev', icon: 'Settings' },
  { id: '09', name: 'Comparador de Diferenças', description: 'Compara blocos de código/texto e destaca diferenças.', category: 'Dev', icon: 'FileDiff' },
  { id: '10', name: 'Conversor Base64 Imagem', description: 'Transforma imagens em strings Base64 e vice-versa instantaneamente.', category: 'Dev', icon: 'Image' },
  { id: '11', name: 'Conversor de cURL para JS', description: 'Converte comandos cURL em código JavaScript pronto.', category: 'Dev', icon: 'Terminal' },
  { id: '12', name: 'Gerador de Layout CSS', description: 'Interface visual para montar layouts Grid/Flexbox e exportar CSS.', category: 'Design', icon: 'Layout' },
  { id: '13', name: 'Gerador de Sitemap XML', description: 'Gera XML de sitemap a partir de uma lista de URLs.', category: 'Dev', icon: 'Map' },
  { id: '14', name: 'Prettier no Navegador', description: 'Formata JS/CSS/HTML usando Web Workers localmente.', category: 'Dev', icon: 'Sparkles' },
  { id: '15', name: 'Conversor YAML/JSON', description: 'Conversão bidirecional entre YAML e JSON.', category: 'Dev', icon: 'RefreshCw' },
  { id: '16', name: 'Simulador de API', description: 'Gera JSON de exemplo baseado em regras de negócio.', category: 'Dev', icon: 'Cpu' },
  { id: '17', name: 'Editor Markdown Online', description: 'Editor de Markdown com renderização em tempo real.', category: 'Dev', icon: 'FileText' },
  { id: '18', name: 'Anonimizador de Logs', description: 'Remove IPs e dados sensíveis de logs via Regex.', category: 'Dev', icon: 'ShieldAlert' },
  { id: '19', name: 'Editor de Caminhos SVG', description: 'Manipulação visual de nós de caminhos SVG.', category: 'Design', icon: 'PenTool' },
  { id: '20', name: 'Guia de Comandos Git', description: 'Busca e sugere comandos Git para cenários comuns.', category: 'Dev', icon: 'GitBranch' },
  { id: '21', name: 'Cortador de Vídeo', description: 'Corta vídeos localmente usando a API WebCodecs.', category: 'Design', icon: 'Video' },
  { id: '22', name: 'Extrator de Cores', description: 'Extrai as cores predominantes de fotos (Canvas API).', category: 'Design', icon: 'Palette' },
  { id: '23', name: 'Gerador de Favicon', description: 'Cria ícones para sites e apps a partir de um PNG.', category: 'Design', icon: 'Globe' },
  { id: '24', name: 'Gerador de Ondas SVG', description: 'Cria ondas animadas em SVG para separadores de sites.', category: 'Design', icon: 'Waves' },
  { id: '25', name: 'Compressor de PDF', description: 'Reduz o tamanho de PDFs comprimindo imagens no navegador.', category: 'Produtividade', icon: 'FileDown' },
  { id: '26', name: 'Efeito Glassmorphism', description: 'Gera código CSS para efeitos de vidro fosco atualizados.', category: 'Design', icon: 'Layers' },
  { id: '27', name: 'Imagem em ASCII', description: 'Converte fotos em arte feita com caracteres de texto.', category: 'Design', icon: 'Type' },
  { id: '28', name: 'Combinador de Fontes', description: 'Sugere combinações visuais do Google Fonts.', category: 'Design', icon: 'Type' },
  { id: '29', name: 'Criador Neumórfico', description: 'Gera sombras para o estilo visual neumórfico moderno.', category: 'Design', icon: 'Box' },
  { id: '30', name: 'Visualizador Lottie', description: 'Testa e ajusta cores de animações Lottie (JSON).', category: 'Design', icon: 'Play' },
  { id: '31', name: 'Gerador de Placeholder', description: 'Gera imagens temporárias personalizadas via Canvas.', category: 'Design', icon: 'Square' },
  { id: '32', name: 'SVG para JSX', description: 'Converte SVGs para componentes React limpos.', category: 'Dev', icon: 'Code' },
  { id: '33', name: 'Divisor de Sprite Sheet', description: 'Corta imagens de ícones em arquivos individuais.', category: 'Design', icon: 'Scissors' },
  { id: '34', name: 'Onda de Áudio', description: 'Gera gráfico de onda sonora em SVG a partir de arquivos de áudio.', category: 'Design', icon: 'Activity' },
  { id: '35', name: 'Filtros CSS Online', description: 'Testa filtros (sépia, desfoque) e exporta classes CSS.', category: 'Design', icon: 'Sliders' },
  { id: '36', name: 'Calculadora de Proporção', description: 'Calcula proporções para vídeos e imagens (16:9, etc).', category: 'Design', icon: 'Maximize' },
  { id: '37', name: 'Malha de Gradiente', description: 'Cria gradientes complexos com múltiplos pontos.', category: 'Design', icon: 'Wind' },
  { id: '38', name: 'Prévia de Fontes', description: 'Visualiza ícones de arquivos .ttf ou .woff.', category: 'Design', icon: 'Type' },
  { id: '39', name: 'Conversor WebP em Lote', description: 'Conversão em massa para WebP diretamente no navegador.', category: 'Design', icon: 'FileImage' },
  { id: '40', name: 'Efeito de Retícula', description: 'Aplica efeito de retícula estilo retrô (dithering) em fotos.', category: 'Design', icon: 'Grid' },
  { id: '41', name: 'Timer Pomodoro', description: 'Timer de foco com notificações e sons locais.', category: 'Produtividade', icon: 'Timer' },
  { id: '42', name: 'Contador de Palavras', description: 'Estatísticas de texto e densidade de palavras em tempo real.', category: 'Produtividade', icon: 'Hash' },
  { id: '43', name: 'Tradutor de Braille', description: 'Converte texto para uma representação visual de Braille.', category: 'Produtividade', icon: 'Dot' },
  { id: '44', name: 'Tradutor de Código Morse', description: 'Converte texto em Morse com suporte a luz e som.', category: 'Produtividade', icon: 'Zap' },
  { id: '45', name: 'Força da Senha', description: 'Avalia a segurança das suas senhas localmente.', category: 'Segurança', icon: 'Lock' },
  { id: '46', name: 'Gerador de Chaves', description: 'Gera chaves aleatórias seguras para criptografia.', category: 'Segurança', icon: 'Key' },
  { id: '47', name: 'Check-list de Viagem', description: 'Interativa lista de viagem pronta para impressão.', category: 'Produtividade', icon: 'CheckSquare' },
  { id: '48', name: 'Cronômetro para Reuniões', description: 'Controle o tempo de suas reuniões e standups.', category: 'Produtividade', icon: 'Users' },
  { id: '49', name: 'Conversor de Unidades', description: 'Conversor universal de medidas que funciona offline.', category: 'Ciência', icon: 'Ruler' },
  { id: '50', name: 'Gerador de QR Code', description: 'Cria QR codes para Wi-Fi, links ou contatos.', category: 'Produtividade', icon: 'QrCode' },
  { id: '51', name: 'Leitor de Voz (TTS)', description: 'Transforma texto em fala usando as vozes do sistema.', category: 'Produtividade', icon: 'Volume2' },
  { id: '52', name: 'Transcrição de Áudio (STT)', description: 'Transcreve sua fala em tempo real para texto.', category: 'Produtividade', icon: 'Mic' },
  { id: '53', name: 'Calculadora de Dívidas', description: 'Simulador financeiro para cálculo de parcelas e juros.', category: 'Produtividade', icon: 'DollarSign' },
  { id: '54', name: 'Conversor de Bases', description: 'Conversão entre Binário, Hexadecimal e Decimal.', category: 'Ciência', icon: 'Binary' },
  { id: '55', name: 'Lorem Ipsum Personalizado', description: 'Gerador de texto fictício com temas variados.', category: 'Produtividade', icon: 'FileText' },
  { id: '56', name: 'Formatação de Texto', description: 'Muda textos para CamelCase, snake_case, e mais.', category: 'Dev', icon: 'Type' },
  { id: '57', name: 'Gravador de Tela', description: 'Grava sua tela ou abas e baixa o vídeo localmente.', category: 'Produtividade', icon: 'Monitor' },
  { id: '58', name: 'Metrônomo Virtual', description: 'Metrônomo para músicos com ajuste preciso de BPM.', category: 'Diversos', icon: 'Music' },
  { id: '59', name: 'Markdown para PDF', description: 'Transforma Markdown em documentos PDF formatados.', category: 'Produtividade', icon: 'FileText' },
  { id: '60', name: 'Política de Privacidade', description: 'Gera rascunhos de políticas de privacidade via formulário.', category: 'Produtividade', icon: 'ShieldCheck' },
  { id: '61', name: 'Tabela Periódica', description: 'Tabela interativa com as propriedades químicas.', category: 'Ciência', icon: 'Atom' },
  { id: '62', name: 'Simulador de Gravidade', description: 'Sandbox de órbitas planetárias em 2D.', category: 'Ciência', icon: 'Orbit' },
  { id: '63', name: 'Codon para Proteína', description: 'Converte sequências de DNA em cadeias de proteínas.', category: 'Ciência', icon: 'Dna' },
  { id: '64', name: 'Sandbox de Grafos', description: 'Testa algoritmos de caminho mínimo em grafos.', category: 'Ciência', icon: 'Network' },
  { id: '65', name: 'Circuitos Lógicos', description: 'Conecta portas lógicas (AND, OR) para criar circuitos.', category: 'Ciência', icon: 'CircuitBoard' },
  { id: '66', name: 'Visualizador de Frações', description: 'Representação visual pedagógica de frações.', category: 'Ciência', icon: 'PieChart' },
  { id: '67', name: 'Conversor de Romanos', description: 'Converte números decimais para o sistema romano.', category: 'Ciência', icon: 'Hash' },
  { id: '68', name: 'Sorteador de Nomes', description: 'Sorteia nomes aleatórios a partir de uma lista.', category: 'Produtividade', icon: 'Shuffle' },
  { id: '69', name: 'Flashcards de Estudo', description: 'Crie e revise flashcards para estudos rápidos.', category: 'Produtividade', icon: 'CreditCard' },
  { id: '70', name: 'Calculadora de IMC', description: 'Cálculo de índice de massa corporal instantâneo.', category: 'Ciência', icon: 'Scale' },
  { id: '71', name: 'Simulador de Projéteis', description: 'Calcula trajetórias de projéteis e lançamentos.', category: 'Ciência', icon: 'ArrowUpRight' },
  { id: '72', name: 'Visualizador de Átomos', description: 'Desenha a estrutura atômica de cada elemento.', category: 'Ciência', icon: 'Circle' },
  { id: '73', name: 'Teste de Reflexo', description: 'Mede seu tempo de reação em milisegundos.', category: 'Diversos', icon: 'Zap' },
  { id: '74', name: 'Medidor de Distância', description: 'Mede distância entre pontos reais em um mapa.', category: 'Ciência', icon: 'MapPin' },
  { id: '75', name: 'Velocidade de Digitação', description: 'Teste sua velocidade de digitação em WPM.', category: 'Diversos', icon: 'Keyboard' },
  { id: '76', name: 'Criptografia AES', description: 'Criptografa texto com senha usando AES-256 local.', category: 'Segurança', icon: 'Lock' },
  { id: '77', name: 'Gerador de Hash', description: 'Gera hashes SHA ou MD5 para verificar integridade.', category: 'Segurança', icon: 'Fingerprint' },
  { id: '78', name: 'Esteganografia', description: 'Esconde mensagens secretas de texto dentro de imagens.', category: 'Segurança', icon: 'EyeOff' },
  { id: '79', name: 'Mensagem Autoexcluível', description: 'Cria link com mensagem que some após a leitura.', category: 'Segurança', icon: 'Bomb' },
  { id: '80', name: 'Gerador de Passphrase', description: 'Gera senhas seguras baseadas em palavras (Diceware).', category: 'Segurança', icon: 'Shield' },
  { id: '81', name: 'Autenticador TOTP', description: 'Gera códigos de autenticação 2FA localmente.', category: 'Segurança', icon: 'Smartphone' },
  { id: '82', name: 'Chaves SSH', description: 'Gera pares de chaves pública e privada com segurança.', category: 'Segurança', icon: 'Key' },
  { id: '83', name: 'Limpar Metadados (EXIF)', description: 'Remove a localização e dados privados das fotos.', category: 'Segurança', icon: 'ImageOff' },
  { id: '84', name: 'Triturador de Arquivos', description: 'Sobrescreve dados de arquivos para deleção segura.', category: 'Segurança', icon: 'Trash2' },
  { id: '85', name: 'Decodificador CSR', description: 'Analisa arquivos de solicitação de certificado SSL.', category: 'Segurança', icon: 'FileCheck' },
  { id: '86', name: 'Sudoku Online', description: 'Resolve e cria tabuleiros de Sudoku na hora.', category: 'Diversos', icon: 'Grid' },
  { id: '87', name: 'Teclado Piano', description: 'Toca piano usando as teclas do seu computador.', category: 'Diversos', icon: 'Music' },
  { id: '88', name: 'Gerador de Memes', description: 'Editor ultra rápido de memes com drag & drop.', category: 'Diversos', icon: 'Laugh' },
  { id: '89', name: 'Dados de RPG', description: 'Simula rolagem de dados (D20, D12) com histórico.', category: 'Diversos', icon: 'Dice5' },
  { id: '90', name: 'Sons 8-Bit', description: 'Cria efeitos sonoros retrô de forma intuitiva.', category: 'Diversos', icon: 'VolumeX' },
  { id: '91', name: 'Pixel Art', description: 'Crie e exporte desenhos pixelados em PNG.', category: 'Design', icon: 'Grid3X3' },
  { id: '92', name: 'Gerador de Labirintos', description: 'Gera labirintos aleatórios perfeitos para imprimir.', category: 'Diversos', icon: 'Activity' },
  { id: '93', name: 'Solucionador de Anagramas', description: 'Descobre todas as palavras ocultas nas letras.', category: 'Diversos', icon: 'Type' },
  { id: '94', name: 'Buscador de Rimas', description: 'Dicionário local focado em composição e rimas.', category: 'Diversos', icon: 'Music' },
  { id: '95', name: 'Gerador de Siglas', description: 'Gera siglas e acrônimos a partir de qualquer frase.', category: 'Produtividade', icon: 'Type' },
  { id: '96', name: 'Leitor de Ebook', description: 'Leitor leve para arquivos EPUB no seu navegador.', category: 'Produtividade', icon: 'BookOpen' },
  { id: '97', name: 'Legendas VTT para SRT', description: 'Converte formatos de legenda de forma instantânea.', category: 'Dev', icon: 'Subtitles' },
  { id: '98', name: 'Capturador de Web', description: 'Limpa páginas web para uma impressão perfeita.', category: 'Produtividade', icon: 'Printer' },
  { id: '99', name: 'Leitor de Código de Barras', description: 'Escaneia códigos de barras usando sua câmera.', category: 'Produtividade', icon: 'Barcode' },
  { id: '100', name: 'Gestão de Gastos', description: 'Controle de orçamento rápido que limpa ao fechar.', category: 'Produtividade', icon: 'PieChart' },
  { id: '101', name: 'Mesclar PDF', description: 'Une vários arquivos PDF em um único documento.', category: 'Produtividade', icon: 'Files' },
  { id: '102', name: 'Dividir PDF', description: 'Extrai páginas ou separa um PDF em várias partes.', category: 'Produtividade', icon: 'Scissors' },
  { id: '103', name: 'Imagem para PDF', description: 'Transforma suas fotos em um arquivo PDF organizado.', category: 'Produtividade', icon: 'FileImage' },
  { id: '104', name: 'PDF para Imagem', description: 'Converte cada página do seu PDF em um JPG.', category: 'Produtividade', icon: 'ImageIcon' },
  { id: '105', name: 'Desbloquear PDF', description: 'Remove senhas e restrições de PDF localmente.', category: 'Segurança', icon: 'LockKeyholeOpen' },
  { id: '106', name: 'Proteger PDF', description: 'Adiciona criptografia e senhas aos seus PDFs.', category: 'Segurança', icon: 'LockKeyhole' },
  { id: '107', name: 'PDF para Word', description: 'Converte documentos PDF em arquivos Word editáveis (.docx).', category: 'Produtividade', icon: 'FileText' },
  { id: '108', name: 'Word para PDF', description: 'Transforma arquivos Word (.docx) em documentos PDF.', category: 'Produtividade', icon: 'FileType' },
  { id: '109', name: 'Conversor de Imagem', description: 'Converte imagens entre formatos PNG, JPG, BMP e WEBP instantaneamente.', category: 'Design', icon: 'ImagePlus' },
  { id: '110', name: 'REST Client (Postman)', description: 'Cliente HTTP completo para testar APIs com headers, body e coleções.', category: 'Dev', icon: 'Globe' },
  { id: '111', name: 'QA Test Suite', description: 'Crie planos de teste, execute validações e exporte relatórios de qualidade.', category: 'Dev', icon: 'ListChecks' },
  { id: '112', name: 'Bug Reporter', description: 'Gere relatórios de bugs estruturados e profissionais para Jira ou Slack.', category: 'Dev', icon: 'Bug' },
  { id: '113', name: 'Gerador de CPF', description: 'Gere CPFs válidos para testes de software com ou sem máscara.', category: 'Diversos', icon: 'Fingerprint' },
  { id: '114', name: 'Gerador de CNPJ', description: 'Gere CNPJs válidos e formatados para validação de sistemas empresariais.', category: 'Diversos', icon: 'Briefcase' },
  { id: '115', name: 'Gerador de RG', description: 'Gere números de RG (Registro Geral) fictícios mas válidos para testes.', category: 'Diversos', icon: 'ShieldCheck' },
  { id: '116', name: 'Gerador de CNH', description: 'Gere números de CNH válidos para sistemas de transporte e logística.', category: 'Diversos', icon: 'CreditCard' },
  { id: '117', name: 'Gerador de CEP', description: 'Crie endereços e CEPs brasileiros válidos para testes de API e frete.', category: 'Diversos', icon: 'MapPin' },
  { id: '118', name: 'Gerador PIS/PASEP', description: 'Geração de números PIS/PASEP válidos para sistemas de RH.', category: 'Diversos', icon: 'Users' },
  { id: '119', name: 'Gerador RENAVAM', description: 'Gere códigos RENAVAM válidos para sistemas automotivos.', category: 'Diversos', icon: 'Car' },
  { id: '120', name: 'Inscrição Estadual', description: 'Gere Inscrições Estaduais válidas de todos os estados brasileiros.', category: 'Diversos', icon: 'Hash' },
  { id: '121', name: 'Título de Eleitor', description: 'Gere números de Título de Eleitor válidos seguindo o algoritmo oficial.', category: 'Diversos', icon: 'ClipboardCheck' },
  { id: '122', name: 'Cartão de Crédito', description: 'Gere números de cartão de crédito de várias bandeiras para testes de checkout.', category: 'Diversos', icon: 'CreditCard' },
  { id: '123', name: 'Conta Bancária', description: 'Gere detalhes de contas bancárias (Agência, Conta, DV) para bancos brasileiros.', category: 'Diversos', icon: 'Banknote' },
  { id: '124', name: 'Gerador de Pessoas', description: 'Crie perfis completos de pessoas (Nome, Idade, CPF, Endereço) para testes.', category: 'Diversos', icon: 'UserPlus' },
  { id: '125', name: 'Gerador Empresa', description: 'Crie dados completos de empresas fictícias para homologação.', category: 'Diversos', icon: 'Building2' },
  { id: '126', name: 'Gerador de Veículos', description: 'Gere dados técnicos de veículos (Modelo, Cor, Chassi, RENAVAM).', category: 'Diversos', icon: 'Truck' },
  { id: '127', name: 'Placa de Veículos', description: 'Gere placas Mercosul ou Padrão Antigo válidas para testes.', category: 'Diversos', icon: 'Disc' },
  { id: '128', name: 'Gerador de Nomes', description: 'Crie nomes brasileiros realistas, masculinos, femininos ou aleatórios.', category: 'Diversos', icon: 'Type' },
  { id: '129', name: 'Gerador de Nicks', description: 'Ideias criativas para nicknames de jogos e redes sociais.', category: 'Diversos', icon: 'Ghost' },
  { id: '130', name: 'Letras Diferentes', description: 'Transforme textos em fontes estilizadas e símbolos para redes sociais.', category: 'Diversos', icon: 'Zap' },
  { id: '131', name: 'Símbolos P/ Copiar', description: 'Galeria completa de símbolos, emojis e caracteres especiais prontos para uso.', category: 'Diversos', icon: 'Command' },
  { id: '132', name: 'Números Aleatórios', description: 'Gere sequências de números ou sorteie valores dentro de um intervalo.', category: 'Diversos', icon: 'Binary' },
  { id: '133', name: 'Gerador de Senha', description: 'Crie senhas ultra-seguras com complexidade customizável.', category: 'Segurança', icon: 'Key' },
  { id: '134', name: 'Gerador Certidões', description: 'Gere números de certidão de nascimento, casamento e óbito padrão nacional.', category: 'Diversos', icon: 'FileText' },
  { id: '135', name: 'Gerador de Currículo', description: 'Crie um currículo profissional em PDF rapidamente com preenchimento guiado.', category: 'Produtividade', icon: 'ScrollText' },
  { id: '999', name: 'Hall da Fama', description: 'Nossa gratidão eterna aos apoiadores que tornam o Canivete possível.', category: 'Comunidade', icon: 'Crown' },
];
