export interface Tool {
  id: string;
  name: string;
  description: string;
  category: 'Dev' | 'Design' | 'Produtividade' | 'Ciência' | 'Segurança' | 'Diversos';
  icon: string;
}

export const TOOLS: Tool[] = [
  { id: '01', name: 'JSON-to-Zod Schema', description: 'Transforma JSON em schemas de validação Zod (TS).', category: 'Dev', icon: 'Code2' },
  { id: '02', name: 'Regex Visualizer', description: 'Explica graficamente como uma expressão regular funciona.', category: 'Dev', icon: 'Search' },
  { id: '03', name: 'SQL Query Beautifier', description: 'Formata queries SQL complexas localmente.', category: 'Dev', icon: 'Database' },
  { id: '04', name: 'CSV to HTML Table', description: 'Converte arquivos CSV em tabelas HTML estilizadas.', category: 'Dev', icon: 'Table' },
  { id: '05', name: 'JWT Decoder Offline', description: 'Decodifica tokens JWT sem enviar dados ao servidor.', category: 'Dev', icon: 'Key' },
  { id: '06', name: 'Cron Job Visualizer', description: 'Traduz expressões de cron para linguagem humana.', category: 'Dev', icon: 'Clock' },
  { id: '07', name: 'HTML Entity Encoder', description: 'Converte caracteres especiais em entidades HTML.', category: 'Dev', icon: 'FileCode' },
  { id: '08', name: 'Env File Generator', description: 'Interface visual para criar arquivos .env baseados em templates.', category: 'Dev', icon: 'Settings' },
  { id: '09', name: 'Diff Checker', description: 'Compara blocos de código/texto e destaca diferenças.', category: 'Dev', icon: 'FileDiff' },
  { id: '10', name: 'Base64 Image Preview', description: 'Converte Base64 para visualização de imagem instantânea.', category: 'Dev', icon: 'Image' },
  { id: '11', name: 'CURL to Fetch/Axios', description: 'Converte comandos CURL em código JavaScript pronto.', category: 'Dev', icon: 'Terminal' },
  { id: '12', name: 'CSS Grid/Flex Generator', description: 'Interface visual para montar layouts e exportar CSS.', category: 'Design', icon: 'Layout' },
  { id: '13', name: 'Sitemap XML Creator', description: 'Gera XML de sitemap a partir de lista de URLs.', category: 'Dev', icon: 'Map' },
  { id: '14', name: 'Browser Prettier', description: 'Formata JS/CSS/HTML usando Web Workers.', category: 'Dev', icon: 'Sparkles' },
  { id: '15', name: 'YAML to JSON', description: 'Conversão bidirecional entre YAML e JSON.', category: 'Dev', icon: 'RefreshCw' },
  { id: '16', name: 'API Response Mocker', description: 'Gera JSON de exemplo baseado em regras de negócio.', category: 'Dev', icon: 'Cpu' },
  { id: '17', name: 'Markdown Live Preview', description: 'Editor de Markdown com renderização em tempo real.', category: 'Dev', icon: 'FileText' },
  { id: '18', name: 'Log Anonymizer', description: 'Remove IPs e dados sensíveis de logs via Regex.', category: 'Dev', icon: 'ShieldAlert' },
  { id: '19', name: 'SVG Path Editor', description: 'Manipulação visual de nós de caminhos SVG.', category: 'Design', icon: 'PenTool' },
  { id: '20', name: 'Git Command Helper', description: 'Busca e sugere comandos Git para cenários comuns.', category: 'Dev', icon: 'GitBranch' },
  { id: '21', name: 'Video Trimmer', description: 'Corta vídeos localmente usando a API WebCodecs.', category: 'Design', icon: 'Video' },
  { id: '22', name: 'Color Palette Extractor', description: 'Extrai cores predominantes de fotos (Canvas API).', category: 'Design', icon: 'Palette' },
  { id: '23', name: 'Favicon Generator', description: 'Cria ícones para web/apps a partir de um PNG.', category: 'Design', icon: 'Globe' },
  { id: '24', name: 'SVG Wave Generator', description: 'Cria ondas animadas em SVG para divisores de sites.', category: 'Design', icon: 'Waves' },
  { id: '25', name: 'PDF Compressor', description: 'Reduz tamanho de PDFs comprimindo imagens no client.', category: 'Produtividade', icon: 'FileDown' },
  { id: '26', name: 'Glassmorphism UI', description: 'Gera código CSS para efeitos de vidro fosco.', category: 'Design', icon: 'Layers' },
  { id: '27', name: 'Image-to-ASCII Art', description: 'Converte fotos em arte de caracteres de texto.', category: 'Design', icon: 'Type' },
  { id: '28', name: 'Font Pairer', description: 'Sugere combinações visuais do Google Fonts.', category: 'Design', icon: 'Type' },
  { id: '29', name: 'Neumorphism Creator', description: 'Gera sombras para o estilo visual neumórfico.', category: 'Design', icon: 'Box' },
  { id: '30', name: 'Lottie Previewer', description: 'Testa e ajusta cores de animações Lottie (JSON).', category: 'Design', icon: 'Play' },
  { id: '31', name: 'Placeholder Gen', description: 'Gera imagens temporárias customizadas via Canvas.', category: 'Design', icon: 'Square' },
  { id: '32', name: 'SVG-to-JSX', description: 'Converte SVGs para componentes React limpos.', category: 'Dev', icon: 'Code' },
  { id: '33', name: 'Sprite Sheet Splitter', description: 'Corta imagens de ícones em arquivos individuais.', category: 'Design', icon: 'Scissors' },
  { id: '34', name: 'Audio Waveform Gen', description: 'Gera gráfico de onda sonora em SVG a partir de MP3.', category: 'Design', icon: 'Activity' },
  { id: '35', name: 'CSS Filter Playground', description: 'Testa filtros (sepia, blur) e exporta classes CSS.', category: 'Design', icon: 'Sliders' },
  { id: '36', name: 'Aspect Ratio Calc', description: 'Calcula proporções para vídeos e imagens (16:9, etc).', category: 'Design', icon: 'Maximize' },
  { id: '37', name: 'Gradient Mesh Builder', description: 'Cria gradientes complexos com múltiplos pontos.', category: 'Design', icon: 'Wind' },
  { id: '38', name: 'Icon Font Previewer', description: 'Visualiza ícones de arquivos .ttf ou .woff.', category: 'Design', icon: 'Type' },
  { id: '39', name: 'WebP Bulk Converter', description: 'Conversão em lote para WebP no navegador.', category: 'Design', icon: 'FileImage' },
  { id: '40', name: 'Dither Image Effect', description: 'Aplica efeito de retícula estilo retro em fotos.', category: 'Design', icon: 'Grid' },
  { id: '41', name: 'Pomodoro Timer', description: 'Timer de foco com notificações locais.', category: 'Produtividade', icon: 'Timer' },
  { id: '42', name: 'Word/Char Counter', description: 'Estatísticas de texto e densidade de palavras.', category: 'Produtividade', icon: 'Hash' },
  { id: '43', name: 'Braille Translator', description: 'Converte texto para representação visual de Braille.', category: 'Produtividade', icon: 'Dot' },
  { id: '44', name: 'Morse Code Flasher', description: 'Converte texto em Morse (luz ou som).', category: 'Produtividade', icon: 'Zap' },
  { id: '45', name: 'Password Strength', description: 'Avalia segurança de senhas localmente.', category: 'Segurança', icon: 'Lock' },
  { id: '46', name: 'Secure Key Gen', description: 'Gera chaves aleatórias para criptografia.', category: 'Segurança', icon: 'Key' },
  { id: '47', name: 'Travel Checklist', description: 'Lista de viagem interativa e imprimível.', category: 'Produtividade', icon: 'CheckSquare' },
  { id: '48', name: 'Standup Timer', description: 'Cronômetro para reuniões ágeis.', category: 'Produtividade', icon: 'Users' },
  { id: '49', name: 'Unit Converter', description: 'Conversor universal de medidas (offline).', category: 'Ciência', icon: 'Ruler' },
  { id: '50', name: 'QR Code Generator', description: 'Gera QR codes para Wi-Fi, links ou contatos.', category: 'Produtividade', icon: 'QrCode' },
  { id: '51', name: 'TTS Tester', description: 'Usa vozes do OS para ler textos digitados.', category: 'Produtividade', icon: 'Volume2' },
  { id: '52', name: 'STT Notebook', description: 'Transcreve fala em tempo real (Web Speech API).', category: 'Produtividade', icon: 'Mic' },
  { id: '53', name: 'Debt Payoff Calc', description: 'Simulador financeiro para cálculo de parcelas/juros.', category: 'Produtividade', icon: 'DollarSign' },
  { id: '54', name: 'Base Converter', description: 'Conversão entre Binário, Hex e Decimal.', category: 'Ciência', icon: 'Binary' },
  { id: '55', name: 'Lorem Ipsum Custom', description: 'Gerador de texto mudo com temas variados.', category: 'Produtividade', icon: 'FileText' },
  { id: '56', name: 'Case Converter', description: 'Muda texto para CamelCase, Snake_case, etc.', category: 'Dev', icon: 'Type' },
  { id: '57', name: 'Screen Recorder', description: 'Grava tela/aba e baixa o arquivo (getDisplayMedia).', category: 'Produtividade', icon: 'Monitor' },
  { id: '58', name: 'Virtual Metronome', description: 'Metrônomo para músicos com ajuste de BPM.', category: 'Diversos', icon: 'Music' },
  { id: '59', name: 'Markdown-to-PDF', description: 'Transforma Markdown em PDF formatado para impressão.', category: 'Produtividade', icon: 'FileText' },
  { id: '60', name: 'Privacy Generator', description: 'Rascunho de política de privacidade via formulário.', category: 'Produtividade', icon: 'ShieldCheck' },
  { id: '61', name: 'Periodic Table', description: 'Tabela interativa com propriedades químicas.', category: 'Ciência', icon: 'Atom' },
  { id: '62', name: 'Gravity Simulator', description: 'Sandbox de órbitas planetárias 2D.', category: 'Ciência', icon: 'Orbit' },
  { id: '63', name: 'Genetic Translator', description: 'Converte sequências de DNA em proteínas.', category: 'Ciência', icon: 'Dna' },
  { id: '64', name: 'Graph Sandbox', description: 'Testa algoritmos de caminho mínimo em grafos.', category: 'Ciência', icon: 'Network' },
  { id: '65', name: 'Logic Gate Sim', description: 'Conecta portas lógicas (AND, OR) para circuitos.', category: 'Ciência', icon: 'CircuitBoard' },
  { id: '66', name: 'Fraction Visualizer', description: 'Representação visual de frações matemáticas.', category: 'Ciência', icon: 'PieChart' },
  { id: '67', name: 'Roman Numeral Conv', description: 'Converte números comuns para sistema romano.', category: 'Ciência', icon: 'Hash' },
  { id: '68', name: 'Name Randomizer', description: 'Sorteador para listas coladas pelo usuário.', category: 'Produtividade', icon: 'Shuffle' },
  { id: '69', name: 'Single-Session Cards', description: 'Flashcards para estudo rápido sem persistência.', category: 'Produtividade', icon: 'CreditCard' },
  { id: '70', name: 'BMI Calculator', description: 'Cálculo de IMC com feedback instantâneo.', category: 'Ciência', icon: 'Scale' },
  { id: '71', name: 'Projectile Simulator', description: 'Calcula trajetórias de projéteis (física).', category: 'Ciência', icon: 'ArrowUpRight' },
  { id: '72', name: 'Atom Visualizer', description: 'Desenha estrutura atômica conforme o elemento.', category: 'Ciência', icon: 'Circle' },
  { id: '73', name: 'Reaction Timer', description: 'Testa milissegundos de reação do usuário.', category: 'Diversos', icon: 'Zap' },
  { id: '74', name: 'Map Distancer', description: 'Mede distância entre pontos num mapa (Leaflet).', category: 'Ciência', icon: 'MapPin' },
  { id: '75', name: 'Typing Speed Test', description: 'Teste de digitação com cálculo de WPM.', category: 'Diversos', icon: 'Keyboard' },
  { id: '76', name: 'AES Encryptor', description: 'Criptografa texto com senha usando AES-256 local.', category: 'Segurança', icon: 'Lock' },
  { id: '77', name: 'Hash Generator', description: 'Gera hashes SHA/MD5 para verificação de arquivos.', category: 'Segurança', icon: 'Fingerprint' },
  { id: '78', name: 'Steganography Tool', description: 'Esconde mensagens de texto dentro de imagens.', category: 'Segurança', icon: 'EyeOff' },
  { id: '79', name: 'Self-Destruct Msg', description: 'Link com mensagem criptografada na própria Hash.', category: 'Segurança', icon: 'Bomb' },
  { id: '80', name: 'Word Passphrase', description: 'Gera senhas seguras baseadas em palavras (Diceware).', category: 'Segurança', icon: 'Shield' },
  { id: '81', name: 'TOTP Web Authenticator', description: 'Gera códigos 2FA via chave secreta localmente.', category: 'Segurança', icon: 'Smartphone' },
  { id: '82', name: 'SSH Key Generator', description: 'Cria pares de chaves pública/privada no browser.', category: 'Segurança', icon: 'Key' },
  { id: '83', name: 'Exif Data Remover', description: 'Limpa localização e metadados de fotos.', category: 'Segurança', icon: 'ImageOff' },
  { id: '84', name: 'File Shredder Sim', description: 'Sobrescreve dados de arquivos antes da exclusão.', category: 'Segurança', icon: 'Trash2' },
  { id: '85', name: 'CSR Decoder', description: 'Lê arquivos de solicitação de certificado SSL.', category: 'Segurança', icon: 'FileCheck' },
  { id: '86', name: 'Sudoku Solver', description: 'Resolve tabuleiros de Sudoku instantaneamente.', category: 'Diversos', icon: 'Grid' },
  { id: '87', name: 'Keyboard Piano', description: 'Transforma o teclado em sintetizador (Web Audio).', category: 'Diversos', icon: 'Music' },
  { id: '88', name: 'Meme Gen Express', description: 'Editor rápido de memes com drag & drop.', category: 'Diversos', icon: 'Laugh' },
  { id: '89', name: 'Dice Roller RPG', description: 'Simulador de dados (D20, D12) com histórico.', category: 'Diversos', icon: 'Dice5' },
  { id: '90', name: '8-Bit FX Maker', description: 'Cria sons de jogos (pulo, explosão) via sliders.', category: 'Diversos', icon: 'VolumeX' },
  { id: '91', name: 'Pixel Art Canvas', description: 'Grade para desenho pixelado e exportação PNG.', category: 'Design', icon: 'Grid3X3' },
  { id: '92', name: 'Maze Generator', description: 'Gera labirintos aleatórios para impressão.', category: 'Diversos', icon: 'Activity' },
  { id: '93', name: 'Anagram Solver', description: 'Encontra palavras escondidas em letras embaralhadas.', category: 'Diversos', icon: 'Type' },
  { id: '94', name: 'Rhyme Finder', description: 'Dicionário local de rimas para compositores.', category: 'Diversos', icon: 'Music' },
  { id: '95', name: 'Acronym Creator', description: 'Gera acrônimos a partir de frases.', category: 'Produtividade', icon: 'Type' },
  { id: '96', name: 'Ebook Reader', description: 'Leitor de arquivos EPUB direto no navegador.', category: 'Produtividade', icon: 'BookOpen' },
  { id: '97', name: 'VTT to SRT', description: 'Conversor de formatos de legenda local.', category: 'Dev', icon: 'Subtitles' },
  { id: '98', name: 'Print Web Clipper', description: 'Limpa HTML para impressão amigável.', category: 'Produtividade', icon: 'Printer' },
  { id: '99', name: 'Barcode Scanner', description: 'Lê códigos de barras via Webcam.', category: 'Produtividade', icon: 'Barcode' },
  { id: '100', name: 'Burner Budget', description: 'Planilha financeira temporária (limpa ao fechar).', category: 'Produtividade', icon: 'PieChart' },
];
